---
title: "Updating Positron"
---

Positron does not currently have a built-in update mechanism; you can [track our work on this feature on GitHub](https://github.com/posit-dev/positron/issues/1837). In the meantime, there are a few helpers available to you to manage manual updates.

## macOS

There is a shell script available that you can use to download and install the latest version. First, download the update script and mark it executable:

```sh
curl https://gist.githubusercontent.com/juliasilge/a74883871e98afe67b01cd9125b104c7/raw/14e447e9fa0aaa858050720f177ed011b059a115/update-positron.sh -o update-positron.sh

chmod u+x update-positron.sh
```

You can optionally put the script on your `$PATH` so you can run it from any directory. You only need to download and set up the shell script like this one time.

Then you can download and install the latest version of Positron via:

```sh
./update-positron.sh 
```

:::{.callout-note}
Unfortunately, this approach does not check your current version of Positron; it will _always_ download and install the latest version.
:::

## Windows

We don't yet officially maintain Positron on Windows package managers, but you can install the latest version of Positron via [scoop](https://scoop.sh/) or [winget](https://learn.microsoft.com/en-us/windows/package-manager/) thanks to the efforts of community maintainers.

### Scoop Package Manager

```powershell
# Add the bucket that has Positron (only need to do this once)
scoop bucket add r-bucket https://github.com/cderv/r-bucket.git

# install 
scoop install positron

# update
scoop update positron
```

This bucket is managed by [Christophe Dervieux](https://github.com/cderv/r-bucket#positron).

### Winget Package Manager

```powershell
# install
winget install --id Posit.Positron

# upgrade 
winget upgrade --id Posit.Positron
```

This is community maintained, via [automated PR to the central manifest repository](https://github.com/microsoft/winget-pkgs/tree/master/manifests/p/Posit/Positron).