extends: substitution
message: "In general, don't use abbreviations. Use '%s' instead of '%s'."
ignorecase: false
level: suggestion
action:
  name: replace
swap:
  'admin(?!\.)': administrator
# ... with the exception of these:
exceptions:
#doesn't seem to be working, maybe because it is two words?  - Admin CLI