extends: conditional
message: "'%s' has no definition."
link: https://docs.microsoft.com/en-us/style-guide/acronyms
level: suggestion
ignorecase: false
# Ensures that the existence of 'first' implies the existence of 'second'.
first: '\b([A-Z]{3,5})\b'
second: '(?:\b[A-Z][a-z]+ )+\(([A-Z]{3,5})\)'
# ... with the exception of these:
exceptions:
  - API
  - AWS
  - APIs
  - ASP
  - CLI
  - CPU
  - CSS
  - CSV
  - DEBUG
  - DOM
  - DPI
  - FAQ
  - GCC
  - GDB
  - GET
  - GPU
  - GTK
  - GUI
  - HTML
  - HTTP
  - HTTPS
  - IDE
  - JAR
  - JSON
  - JSX
  - LDAP
  - LDAPS
  - LESS
  - LLDB
  - NET
  - NOTE
  - NVDA
  - OSS
  - PATH
  - PDF
  - PHP
  - POST
  - RAM
  - REPL
  - RSA
  - SCM
  - SCSS
  - SDK
  - SQL
  - SSH
  - SSL
  - SVG
  - TBD
  - TCP
  - TODO
  - URI
  - URL
  - USB
  - UTF
  - XML
  - XSS
  - YAML
  - ZIP
  - RHEL
  - LTS
  - SLES
  - ODBC
  - TLS
  - CentOS
  - NFS
  - CRAN
  - UID
  - GID
  - SLA
  - SUSE
  - SUSE 15 SP4
  - SUSE 15 SP3
  - CVE
  - BLAS
  - YARN
  - OBDC
  - DEB
  - RPM
  - RDS
  - DSN
  - WGCNA
  - OIDC
  - SAML
  - DNS
  - CDN
  - PAM
  - SSO