extends: existence
message: "Don't use '%s'. See the A-Z word list for details."
# See the Style Guide. 
link: https://positpbc.atlassian.net/wiki/spaces/ENG/pages/594509972/Posit+Documentation+Style+Guide#Word-list-&-terms[inlineExtension]
ignorecase: true
level: suggestion
tokens:
  - and so on
  - Note that
  - Please note
