extends: capitalization
message: "'%s' should use sentence-style capitalization."
link: https://docs.microsoft.com/en-us/style-guide/capitalization
level: error
scope: 
  - heading.h2
  - heading.h3
  - heading.h4
  - heading.h5
  - heading.h6
  - heading.h7
  - heading.h8
match: $sentence
indicators:
  - ':'
exceptions:
  - Azure
  - CLI
  - Code
  - Cosmos
  - Docker
  - Emmet
  - I
  - Kubernetes
  - Linux
  - macOS
  - Marketplace
  - MongoDB
  - REPL
  - Studio
  - TypeScript
  - URLs
  - Visual
  - VS
  - Windows
  - Shiny Server Pro
  - Posit Team
  - Posit Connect
  - Posit Package Manager
  - Posit Workbench
  - Workbench
  - Connect
  - Package Manager
  - AWS Marketplace
  - Google Cloud Platform
  - AWS SageMaker
  - Posit Cloud
  - Google Cloud Workstations
  - RStudio Desktop Pro
  - RStudio Desktop
  - RStudio Server
  - RStudio Server Pro
  - AWS
  - GCP
  - EFS
  - I/O
  - vs.
  - EC2
  - Python
  - SUSE
  - SUSE 15 SP3
  - SUSE 15 SP4
  - SUSE 15 SP5
  - Jupyter Kernel
  - Quarto
  - R
  - BLAS
  - R Markdown
  - shinyapps.io
  - Pro Drivers
  - Posit Professional Drivers
  - ODBC DSNs
  - Linux OS
  - ODBC
  - RStudio Professional Drivers
  - RStudio IDE
  - IDE
  - FAQs
  - DNS
  - SSL
  - CA
  - Local Launcher
  - SUSE 15 SP5/SP6
  - RStudio Server License Server
