extends: existence
message: "Avoid using acronyms in a title or heading."
link: https://positpbc.atlassian.net/wiki/spaces/ENG/pages/594509972/Posit+Documentation+Style+Guide#Word-list-&-terms[inlineExtension]
level: warning
scope: heading
tokens:
  - '[A-Z]{2,4}'
exceptions:
  - AWS
  - GCP
  - EFS
  - MB
  - SUSE
  - SUSE 15 SP4
  - SUSE 15 SP3
  - BLAS
  - ODBC 
  - DSNs
  - OS
  - RPM
  - DEB
  - URL
  - IDE
  - HA
  - DNS
  - SSL
  - CA