extends: substitution
message: "Use '%s' instead of '%s'." 
link: https://positpbc.atlassian.net/wiki/spaces/ENG/pages/594509972/Posit+Documentation+Style+Guide
ignorecase: true
level: error
action:
  name: replace
swap:
  'eg(?!\.)': e.g.
  'ie(?!\.)': i.e.