extends: existence
message: "In general, avoid using [here] when cross-referencing content. Use the section name/document title/guide title, etc."
ignorecase: true
level: error
action:
  name: convert
  params:
    - simple
tokens:
  - 'here'