extends: existence
message: "In general, don't hyphenate '%s'. For example, replace re-install with reinstall and re-use with reuse."
ignorecase: true
level: error
action:
  name: convert
  params:
    - simple
tokens:
  - 're-\w+'
