extends: substitution
message: "Prefer '%s' instead of '%s'."
# term preference should be based on Posit style guide and then microsoft style guide
link: https://positpbc.atlassian.net/wiki/spaces/ENG/pages/594509972/Posit+Documentation+Style+Guide#Word-list-&-terms[inlineExtension], https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/a/adapter
level: suggestion
ignorecase: true
action:
  name: replace
swap:
  "(?:agent|virtual assistant|intelligent personal assistant)": personal digital assistant
  "(?:assembler|machine language)": assembly language
  "(?:drive C:|drive C>|C: drive)": drive C
  "(?:internet bot|web robot)s?": bot(s)
 # "(?:microsoft cloud|the cloud)": cloud
  "(?:mobile|smart) ?phone": phone
  "24/7": every day
  "audio(?:-| )book": audiobook
  "back(?:-| )light": backlight
  "chat ?bots?": chatbot(s)
  checkbox: check box
  uncheck: clear
  mouse: cursor / mouse cursor
  #dialog: dialog box
  #dialog: dialogs
  dropdown: drop-down
  drop down: drop-down
  box: field
  check: select
  type in: type
  #open-source: open source
  e-mail: email
  user interface: user-interface
  sign into: sign in to
  log into: log in to
  adaptor: adapter
  administrate: administer
  afterwards: afterward
  alphabetic: alphabetical
  alphanumerical: alphanumeric
  an URL: a URL
  anti-aliasing: antialiasing
  anti-malware: antimalware
  anti-spyware: antispyware
  anti-virus: antivirus
  appendixes: appendices
  artificial intelligence: AI
  caap: CaaP
  conversation-as-a-platform: conversation as a platform
  eb: EB
  gb: GB
  gbps: Gbps
  kb: KB
  keypress: keystroke
  mb: MB
  pb: PB
  tb: TB
  zb: ZB
  Jupyter Lab: JupyterLab
  #Jupyter Notebooks: Jupyter Notebook
