on: pull_request

name: Vale Lint

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4 

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
      
      - name: Render to generate HTML
        uses: quarto-dev/quarto-actions/render@v2  

      - name: Lint HTML with vale
        uses: errata-ai/vale-action@reviewdog
        with:
          files: _site/
          token: ${{secrets.GITHUB_TOKEN}}